### PR TITLE
Hotfix/append fields

### PR DESCRIPTION
**Pull request by abea**
Addresses #8

### CODE REVIEW

**Comment by austinstarin** [comment]
@bgantick Is there a property that handles this?

**Comment by bgantick** [comment]
`last: true` https://apostrophecms.org/docs/tutorials/getting-started/schema-guide.html#building-schemas-with-code-add-fields-code-and-friends

**Comment by abea** [comment]
Nice. Updated.

**Review by bgantick — APPROVED** [review]

**Comment by stuartromanek** [comment]
who mergin these

**Comment by abea** [comment]
Got it.

**Pull request merged**
