### PR TITLE
og image url needs to be absolute, use data.baseUrl

### PR DESCRIPTION
**Pull request by stuartromanek**

### CODE REVIEW

**Comment by stuartromanek** [comment]
this just doesn't work as-is, right?

**Comment by stuartromanek** [comment]
wow i see i did this a year ago and I guess it wasn't a universal fix .. not sure what to do, this functionality is broken out of the box

**Comment by abea** [comment]
You mean it'd be a BC break even though it's a fix?

**Review by abea — APPROVED** [review]

**Comment by stuartromanek** [comment]
merged and published to npm

**Pull request merged**
